language: r
sudo: false
dist: trusty
cache: packages

warnings_are_errors: true

r_github_packages:
  - jimhester/lintr
  - mlr-org/mlr

notifications:
  email:
    recipients:
      - c.leiber@campus.lmu.de
      - alona.sydorova@campus.lmu.de
      - li.kunlan@campus.lmu.de
on_success: change
on_failure: always