language: r
sudo: false
dist: trusty
cache: packages

warnings_are_errors: true

r_github_packages:
  - jimhester/lintr
  - mlr-org/mlr
  - berndbischl/ParamHelpers

notifications:
  email:
    recipients:
      - c.leiber@campus.lmu.de
      - alona.sydorova@campus.lmu.de
      - li.kunlan@campus.lmu.de
on_success: change
on_failure: always

r_packages:
  - covr

before_install:
  #- sudo apt-get -qq update
  - sudo apt-get install -y libv8-3.14-dev
  
after_success:
  - Rscript -e 'library(covr); codecov()'