---
title: "benchmarkVis - Benchmark Visualizations in R"
author: "Collin Leiber, Alona Sydorova, Kunlan Li"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{benchmarkVis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This vignette is supposed to give you a short and easy introduction into the benchmarkVis package.

The purpose of the package is to provide a flexible and simple to use framework to visualize benchmark results. 

Benchmarking is a good way to compare the performances of different algorithms. To evaluate the results often the same procedures are used. But even though different benchmarks normally contain similar information, the structure can differ significantly. This increases the effort to visualize and analyze them. You have to do the same creation steps over and over again with just a few little changes. At this point the benchmarkVis package comes into play. It aims to convert various formats into a default data table which then can be visualized in multiple ways. 

The package offers several differant plots which range from simple bar charts to complex parallel coordinates plots. All the functionalities are also provided from an interactive shiny application to simplify the workflow even more. This includes comprehensive methods to manipulate the input benchmark data. 

The benchmarks themselves are not generated with this package. They have to be imported from other tools. But no problem, the benchmarkVis package offers several easy ways to integrate benchmark results from your favorite software. Therefore a clearly structured input data format has been defined which is combinable with csv files, R [data.table](https://github.com/Rdatatable/data.table) or directly with R benchmark packages like [mlr](https://github.com/mlr-org/mlr), [microbenchmark](https://github.com/joshuaulrich/microbenchmark/) or [rbenchmark](https://github.com/eddelbuettel/rbenchmark) through different wrappers.

# Input data structure

In this section we will describe the input data structure for the benchmarkVis package. It consists of a table of the following structure:

| problem | problem.parameter | algorithm | algorithm.parameter | replication | replication.parameter | measure.1 | measure.2 | list.1 | list.2 |
|---|---|---|---|---|---|---|---|---|---|
| factor | list | factor | list | factor | list | numeric | numeric | vector | vector |
| mandatory | mandatory | mandatory | mandatory | mandatory | mandatory | optional | optional | optional | optional |

As you can see, each column has a fixed name and data type. Also some of the columns are optional while others are mandatory.
The table can contain any number of measures and lists. It is just important that at least one column of type measure or list is contained and that the column names start with "measure." / "list.".

One special case occurs if you change algorithm parameters through multiple iterations. If this is the case you need to add the numeric field `iteration` to the algorithm.parameters list of the specified algorithm. It is important that this value is defined for every entry of the algorithm and that no value occurs multiple times.

# Import data

As stated before, there are several ways to use your data in the benchmarkVis package.

### Use a csv file 

The most flexible way is to create your benchmark result as a csv file and import the csv file direclty into the package. This is done through:

``` 
csvImport(PATH.TO.CSV.File)
```

There are just a few rules if you choose this import possibility.

* For the parameter lists your input has to be of following structure:
  ```
  "list(numeric.field = variable, character.field = 'example.string')"
  ```
  Beware that a character input in the list needs a extra single quotation! 
* For the vector columns the input needs to look like:
  ```
  "c(value1, value2, value3)"
  ```

If you are still not exactly sure how to design a compatible csv file take a look at the example file `ml.example.csv` at [Link](https://github.com/collinleiber/benchmarkVis/blob/lkl_new_feature/data/ml.example.csv).
After the import a structure check will be run to see if everything is correct.

### Use a wrapper

Another simple way to use your benchmark data is to create your benchmarks with a R package for which a wrapper is contained in the benchmarkVis package. To see a fill list of compatible wrappers use following function:

```
listWrappers()
```

Also for this approach a structure check will run to see if everything is working as intended.

### Use a R data.table

The third option is to create your data.table directly with R. To see if your table is compatible with the benchmarkVis package it is recommended to run a structure check:

```
checkStructure(data.table)
```

This way you can be certain all methods are working properly.

# Create plots

The main feature of the package is to create different kinds of plots. These can roughly be devided into three groups:

* Measure plots
* List plots
* Iteration plots

To see a list with all possible charts use the method:

```
listPlots()
```

If you don't know the needed arguments of a special plot, take a look into the package documentation.

# Shiny application

All the functionalities of the package are also provided from an interactive shiny application. Therefore just open the `ui.R` or `server.ui` file from the shiny directory from RStudio and click the "Run App" button in the upper right. If you do not use RStudio you can load the benchmarkVis package and run the R command `shiny::runApp('shiny')`.

After the shiny applicaion has been started the first step you need to do is to import your data. First select you import data type and then choose the corresponding csv or Rds file. When the upload is finished you can select the `Manipulate table` entry in the menu on the left. There you can execute aggretaions and transformations to transform the table into the desired structure. The transformed table can be saved as csv file to better share your results. 

Next you need to switch to the `Plots` menu, where you can create all kinds of charts. After a plot type has been chosen and all parameters have been defined the plot will be created in the bottom of the screen. Through the usage of the `plotly` package there is a wide range of interaction possibilities. If you want to save a plot for a later comparison you can insert it into the menu on the left by clicking `Save plot`.

# Wiki

If there are questions left, take a look into our [Wiki](https://github.com/collinleiber/benchmarkVis/wiki). There you can find more tips to simplify the usage of the benchmarkVis package.
Should there be no answer to your question or do you find any errors in the software feel free to open an [Issue](https://github.com/collinleiber/benchmarkVis/issues).
